# Generated by Django 5.0.1 on 2024-02-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
