# Generated by Django 5.0.1 on 2024-01-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='persons',
            new_name='person',
        ),
    ]
