# Generated by Django 5.0.1 on 2024-02-06 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
        ('persons', '0003_alter_person_user'),
        ('tickets', '0002_rename_persons_ticket_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='concerts.concert'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='persons.person'),
        ),
    ]
