# Generated by Django 5.0.1 on 2024-02-13 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
        ('persons', '0011_alter_person_user'),
        ('tickets', '0008_ticket_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='concert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts.concert'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
