# Generated by Django 5.0.1 on 2024-02-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_alter_person_user'),
        ('tickets', '0009_alter_ticket_concert_alter_ticket_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
    ]
